config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: :create
  end

  post 'like_post/:id' => 'like_posts#create', as: 'create_like_post'
  delete 'like_post/:id' => 'like_posts#destroy', as: 'destroy_like_post'

  post 'like_comment/:id' => 'like_comments#create', as: 'create_like_comment'
  delete 'like_comment/:id' => 'like_comments#destroy', as: 'destroy_like_comment'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :like_comments
  validates :text, presence: true
end

app/models/like_comment.rb
class LikeComment < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/like_commnent.rb
class LikeCommnent < ApplicationRecord
  belongs_to :comment
  belongs_to :user
end

app/models/like_post.rb
class LikePost < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :like_posts
  has_many :comments
  with_options presence: true do
    validates :title
    validates :description
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }
  has_many :posts
  has_many :comments
  has_many :like_comments, dependent: :destroy
  has_many :like_posts, dependent: :destroy

  def liked_post_by?(post_id)
    like_posts.where(post_id: post_id).exists?
  end

  def liked_comment_by?(comment_id)
    like_comments.where(comment_id: comment_id).exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:create]
  def create
    comment = Comment.create(comment_params)
    redirect_to post_path(comment.post.id)
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/like_comments_controller.rb
class LikeCommentsController < ApplicationController
  before_action :comment_params
  def create
    LikeComment.create(user_id: current_user.id, comment_id: params[:id])
  end

  def destroy
    LikeComment.find_by(user_id: current_user.id, comment_id: params[:id]).destroy
  end

  private

  def comment_params
    @comment = Comment.find(params[:id])
  end
end

app/controllers/like_posts_controller.rb
class LikePostsController < ApplicationController
  before_action :post_params

  def create
    LikePost.create(user_id: current_user.id, post_id: params[:id])
  end

  def destroy
    LikePost.find_by(user_id: current_user.id, post_id: params[:id]).destroy
  end

  private

  def post_params
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_post_user, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:user).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order('created_at DESC')
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to action: :show
    else
      render action: :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :description).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_post_user
    redirect_to root_path if @post.user != current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_comments_helper.rb
module LikeCommentsHelper
end

app/helpers/like_posts_helper.rb
module LikePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ColumnCheck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/like_comments/_like.html.erb
<% if user_signed_in? %>
 <% if current_user.liked_comment_by?(comment.id) %>
   <td>
    <%= link_to destroy_like_comment_path(comment), method: :DELETE, remote: true do %>
    <div class="like-comment-count">
      <span class="fa fa-heart like-btn"><%= comment.like_comments.count %>
    </div>
    <% end %>
  </td>
 <% else %>
   <td>
    <%= link_to create_like_comment_path(comment), method: :POST, remote: true do %>
    <div class="like-comment-count">
      <span class="fa fa-heart-o like-btn"><%= comment.like_comments.count %>
    </div>
    <% end %>
  </td>
 <% end %>
<% end %>

app/views/like_comments/create.js.erb
$('#like_comments_buttons_<%= @comment.id %>').html("<%= j(render partial: 'like_comments/like', locals: {comment: @comment}) %>");

app/views/like_comments/destroy.js.erb
$('#like_comments_buttons_<%= @comment.id %>').html("<%= j(render partial: 'like_comments/like', locals: {comment: @comment}) %>");

app/views/like_posts/_like.html.erb
<% if user_signed_in? %>
 <% if current_user.liked_post_by?(post.id) %>
   <td>
    <%= link_to destroy_like_post_path(post), method: :DELETE, remote: true do %>
    <div class="like-count">
      <span class="fa fa-heart like-btn"><%= post.like_posts.count %>
    </div>
    <% end %>
  </td>
 <% else %>
   <td>
    <%= link_to create_like_post_path(post), method: :POST, remote: true do %>
    <div class="like-count">
      <span class="fa fa-heart-o like-btn"><%= post.like_posts.count %>
    </div>
    <% end %>
  </td>
 <% end %>
<% end %>

app/views/like_posts/create.js.erb
$('#like_posts_buttons_<%= @post.id %>').html("<%= j(render partial: 'like_posts/like', locals: {post: @post}) %>");

app/views/like_posts/destroy.js.erb
$('#like_posts_buttons_<%= @post.id %>').html("<%= j(render partial: 'like_posts/like', locals: {post: @post}) %>");

app/views/posts/edit.html.erb
<%= render 'role/header' %>

<div class="post-content">
  <div class="posts-wrapper">
    <div class="post-red-title">Column<span class="post-orange-title">Check</span></div>
    <div class="post-form">
      <%= form_with model: @post, url: post_path, local: true do |f| %>
      <%= render 'shared/error_messages', model:f.object %>
      <div class="new-post">
        <%= f.text_area :title, class: "post-text", id: "post-title", placeholder: "知りたいカラム名や変数名を入力してください" %>
        <%= f.text_area :description, class: "post-text", id: "post-description", placeholder: "詳細説明を入力してください。" %>
        <%= f.submit "編集する", id:"submit-btn" %>
      </div>
      <% end %>
      
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'role/header' %>
<div class = 'theme-wrapper'>
  <div class = "theme-content">
    <p id = "theme-title">カラムチェック</p>
    <p id = "theme-detail">
      Webアプリケーション作成時や、スキルチェックの際の変数の命名に困った際は
      質問してみよう。<br>また、投稿されたカラムについて自分ならどう名付けるのかを
      コメントすることで仲間の助けになる！
    </p>
  </div>
</div>

<%# 投稿一覧 %>
<ul class='post-lists'>
  <% @posts.each do |post| %>
    <li class="list">
      <%= link_to(post_path(post.id),method: :get)  do %>
      <div class="column-info">
        <div class="column-title">
          <%= post.title %><span class="fa fa-heart index-like"><%= post.like_posts.count %></span>
        </div>     
        <div class="column-description">
          <%= post.description %>
        </div>
      </div>
      <% end %>
    </li>
  <% end %>
<%# 投稿一覧 %>
</ul>

app/views/posts/new.html.erb
<%= render 'role/header' %>

<div class="post-content">
  <div class="posts-wrapper">
    <div class="post-red-title">Column<span class="post-orange-title">Check</span></div>
    <div class="post-form">
      <%= form_with model: @post, url: posts_path, local: true do |f| %>
      <%= render 'shared/error_messages', model:f.object %>
      <div class="new-post">
        <%= f.text_area :title, class: "post-text", id: "post-title", placeholder: "知りたいカラム名や変数名を入力してください" %>
        <%= f.text_area :description, class: "post-text", id: "post-description", placeholder: "詳細説明を入力してください。" %>
        <%= f.submit "投稿する", id:"submit-btn" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<%= render 'role/header' %>

<%# 投稿詳細 %>
<div class="post-show">
    <table class="detail-table">
      <tbody> 
        <tr>
          <th class="detail-post">カラム名</th>
        </tr>
        <tr>
          <td class="detail-value"><%= @post.title %></td>
        </tr>
        <tr>
          <th class="detail-post">詳細</th>
        </tr>
        <tr>
          <td class="detail-value"><%= @post.description %></td>
        </tr>
      </tbody>
      <tr id='like_posts_buttons_<%= @post.id %>'>
        <%= render partial: 'like_posts/like', locals: {post: @post} %>
      </tr>
    </table>
    <% if current_user.id == @post.user_id %>
        <%= link_to 'カラムの編集', edit_post_path(@post.id), method: :get, class: "post-edit-btn" %>
        <%= link_to "カラムの削除", post_path(@post.id), method: :delete, class:"post-destroy" %>
      <% else %>
      <% end %>
  </div>
</div>
<%# 投稿詳細 %>

<%# コメントフォーム %>
  <div class="comment-wrapper">
    <% if user_signed_in? %>
    <div class="comment-form">
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする",row: 4, class: "comment-input" %>
        <%= form.submit "SEND", class: "comment-submit" %>
      <% end %>
    </div>
    <% end %>
<%# コメントフォーム %>

<%# コメント一覧 %>
    <div class="comments">
      <h4>＜コメント一覧＞</h4>
      <% @comments.each do |comment| %>
      <div class="comment-show">
        <p class ="comment-name">
          <%=comment.user.name %>
        </p>
        <div class="comment">
          <p class="comment-text">
            <%= comment.text %>         
          </p>
          <div id='like_comments_buttons_<%= comment.id %>'>
            <%= render partial: 'like_comments/like', locals: {comment: comment} %> 
          </div>
        </div>
      </div>
      <% end %>
<%# コメント一覧 %>
    </div>
  </div>

app/views/role/_header.html.erb
<header id="header-wrapper">
  <%= link_to root_path, id:"root-path" do %>
    <div class="red-title">Column<span class="orange-title">Check</span></div>
  <% end %>
  <form id="header-where" action="/input/" method="get">
    <input type="text" id="top-input" name='i' placeholder="検索したいカラム名を入力してください">
    <button class="search-btn">検索</button>
  </form>
  <ul class="header-right">
  <% if user_signed_in? %>
    <li><%= link_to '投稿する',  new_post_path, class: 'post-btn' %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
  <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: 'login' %></li>
    <li><%= link_to 'サインイン', new_user_registration_path, class: 'signin' %></li>
  <% end %>
  </div>
</header>

app/views/role/_second-header.html.erb
<header id="header-wrapper">
  <%= link_to root_path, id:"root-path" do %>
    <div class="red-title">Column<span class="orange-title">Check</span></div>
  <% end %>
</header>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>